// Myrtavia region data — coordinates are % of the map image (1705×923)

const REGIONS = [
  {
    id: 'icehold',
    name: 'Icehold',
    epithet: 'The Frostkin Reach',
    climate: 'Subarctic · perpetual winter',
    population: '~22,000 (clans)',
    threat: 2,
    ruler: 'Council of the Pale Antler',
    blurb: 'A frozen archipelago of glacial fjords and storm-bitten cliffs. The Frostkin clans carve protective runes into living ice and ride dire-elk along forgotten trade roads. Beneath the floes the Old Leviathans sleep — and the clans pay tribute in song so they sleep on.',
    hooks: [
      'A rune-stone has gone silent. Three villages have not been heard from since.',
      'A whaling captain claims the Leviathan beneath Hoarfrost is dreaming again.',
    ],
    polygon: '0.5,3 10,1.5 20,3 28,7 32,14 28,22 18,30 9,29 3,22 0.5,14',
    labelAt: { x: 18, y: 14 },
    pois: [
      { id: 'hoarfrost', name: 'Hoarfrost Hold',   type: 'city',    x: 13, y: 11.5, note: 'Seat of the Pale Antler. Built atop a living glacier.' },
      { id: 'whitefang', name: 'Whitefang Pass',   type: 'landmark',x: 21, y: 17,   note: 'The only land route inland. Closed nine months of the year.' },
      { id: 'sunkencairn', name: 'Sunken Cairn',  type: 'ruins',   x: 6,  y: 23,   note: 'Pre-Frostkin burial site exposed by a receding floe.' },
    ],
  },
  {
    id: 'neptegia',
    name: 'Neptegia',
    epithet: 'The Hundred Isles',
    climate: 'Temperate maritime',
    population: '~140,000 (scattered)',
    threat: 2,
    ruler: 'The Coral Concord',
    blurb: 'Hundreds of emerald isles strung between coral reefs. The Tidewardens patrol the salt-trade routes from the Coral Spire while pearl-divers chart hidden grottoes. Half the maps lie, the other half are forgeries — and every captain claims to know the way to the Drowned Library.',
    hooks: [
      'A merchant cog returned crewless, its hold full of seawater and pearls.',
      'The Drowned Library has surfaced again. It will be down again by the new moon.',
    ],
    polygon: '20,26 28,22 38,21 48,25 52,33 50,45 44,54 32,56 23,52 19,42 18,32',
    labelAt: { x: 33, y: 38 },
    pois: [
      { id: 'coralspire', name: 'Coral Spire',     type: 'city',     x: 31.5, y: 44, note: 'Capital, grown from a single living coral over four centuries.' },
      { id: 'drowned',    name: 'Drowned Library', type: 'dungeon',  x: 38,   y: 50, note: 'Submerged archive. Surfaces three nights each generation.' },
      { id: 'tidewatch',  name: 'Tidewatch Beacon',type: 'landmark', x: 25,   y: 32, note: 'Northernmost lighthouse. Burns blue when leviathans pass.' },
    ],
  },
  {
    id: 'eldoria',
    name: 'Eldoria',
    epithet: 'The Silver Heartland',
    climate: 'Temperate · long springs',
    population: '~480,000',
    threat: 1,
    ruler: 'The Silver Court at Grande Cidadela',
    blurb: 'The verdant heartland. The Grande Cidadela rises a thousand feet above old-growth forest, and the wandering druid circles answer only to the moon. The Silver Court keeps an uneasy peace between the highland clans and the river-barons — though whispers say the Court itself is hollow.',
    hooks: [
      'A river-baron has been found dead with silver in his mouth and a druid sigil on his door.',
      'The Heir was last seen riding into the Cemitério de Espadas. That was forty days ago.',
    ],
    polygon: '52,13 60,10 70,9 80,12 88,18 90,28 86,38 78,46 68,48 58,46 52,38 50,24',
    labelAt: { x: 70, y: 28 },
    detailMap: 'regions/eldoria.png',
    pois: [
      { id: 'cidadela',     name: 'Grande Cidadela',           type: 'city',     x: 68, y: 24, hideOnWorld: true, note: 'The capital. A thousand-foot spire of pale stone. Seat of the Silver Court.' },
      { id: 'catedral',     name: 'Catedral dos Magos de Ébano', type: 'city',   x: 76, y: 30, note: 'Order of the Ebon Mages. None enter without invitation; few are extended.' },
      { id: 'cemiterio',    name: 'Cemitério de Espadas',      type: 'ruins',    x: 70, y: 17, note: 'Ten thousand swords stand planted in the soil. None has rusted in nine centuries.' },
      { id: 'convergencia', name: 'Floresta da Convergência',  type: 'landmark', x: 63, y: 34, note: 'Where the nine druid circles meet at every solstice.' },
      { id: 'veu',          name: 'Véu da Deusa',              type: 'landmark', x: 84, y: 20, note: 'A grove where time slows. It is said the goddess walked here once.' },
    ],
    detail: {
      width: 1705,
      height: 923,
      hotspots: [
        { id: 'cidadela',     name: 'Grande Cidadela',            type: 'city',     x: 55.8, y: 39, blurb: 'The capital and seat of the Silver Court. Its central spire is visible from every part of central Eldoria.' },
        { id: 'catedral',     name: 'Catedral dos Magos de Ébano', type: 'city',    x: 68.5, y: 41, blurb: 'Cloister-fortress of the Ebon Mages. The cathedral\u2019s nave is unmapped — it changes shape between visits.' },
        { id: 'cemiterio',    name: 'Cemitério de Espadas',       type: 'ruins',    x: 58,   y: 22, blurb: 'Battlefield of the Sundering. Ten thousand swords were driven into the earth and refuse to be drawn.' },
        { id: 'vista_boreal', name: 'Vista Boreal',               type: 'landmark', x: 37,   y: 14, blurb: 'Lighthouse-watch of the northern strait. The lamp burns blue when ill omens approach.' },
        { id: 'veu',          name: 'Véu da Deusa',               type: 'landmark', x: 75,   y: 21, blurb: 'A grove of violet-blooming trees where time slows. Pilgrims age a day in an hour, or an hour in a day.' },
        { id: 'convergencia', name: 'Floresta da Convergência',   type: 'landmark', x: 47,   y: 53, blurb: 'Where the nine druid circles convene at every solstice. The trees remember every word spoken beneath them.' },
        { id: 'drachenfels',  name: 'Vale de Drachenfels',        type: 'ruins',    x: 35.5, y: 51, blurb: 'A dragon-haunted valley. Locals never speak its true name; visitors find their compasses spin idly here.' },
        { id: 'observatorio', name: 'Observatório de Vênus',      type: 'landmark', x: 84.5, y: 51, blurb: 'Stargazers chart the second moon\u2019s slow approach from this isolated tower. Their charts disagree.' },
        { id: 'porto_solar',  name: 'Porto Solar',                type: 'city',     x: 19,   y: 68, blurb: 'Sun-blessed trade port. Its gold-leafed temple is the second-richest in all Myrtavia.' },
        { id: 'salao_almas',  name: 'Salão das Almas',            type: 'city',     x: 19.5, y: 56, blurb: 'The Hall of Souls. A monastery where the dead are remembered for as long as one priest still knows their name.' },
        { id: 'refugio',      name: 'Refúgio de Ébano',           type: 'city',     x: 67,   y: 66, blurb: 'A waystation for travelers between the Court and the Cathedral. Coin runs faster than rumor here.' },
        { id: 'borda',        name: 'Borda do Rei',               type: 'landmark', x: 53.5, y: 68, blurb: 'The King\u2019s Edge — the southernmost mark of the Court\u2019s direct rule. Beyond, custom rules instead of law.' },
        { id: 'bahmut',       name: 'Casa de Bahmut',             type: 'ruins',    x: 38,   y: 73, blurb: 'A keep half-eaten by the forest. Bahmut was a hero, then a tyrant, then forgotten.' },
        { id: 'escarpas',     name: 'Escarpas do Dragão',         type: 'landmark', x: 41,   y: 88, blurb: 'The Dragon Scarps. Sheer cliffs where wyrms once nested; the caves still smell of old smoke.' },
        { id: 'ninho',        name: 'Ninho de Cinzas',            type: 'ruins',    x: 11,   y: 88, blurb: 'The Nest of Ashes. A hatchery long abandoned — or perhaps merely waiting.' },
        { id: 'vigia_coroa',  name: 'Vigia da Coroa',             type: 'landmark', x: 11,   y: 13, blurb: 'Watchtower of the northwestern coast. Whoever holds it sees three days\u2019 sail in every direction.' },
        { id: 'ancoradouro',  name: 'Ancoradouro Real',           type: 'city',     x: 18,   y: 33, blurb: 'The Royal Anchorage. The Silver Court\u2019s deep-water harbor; warships overwinter here.' },
        { id: 'lanca',        name: 'Lança de Neraval',           type: 'ruins',    x: 37,   y: 33, blurb: 'A toppled siege-spear from the Sundering. Locals carve prayers into it for safe travel.' },
        { id: 'alameda',      name: 'Alameda dos Anjos',          type: 'landmark', x: 84,   y: 69, blurb: 'A processional way lined with weeping angels. They turn their heads to watch you pass.' },
      ],
    },
  },
  {
    id: 'miraglia',
    name: 'Miraglia',
    epithet: 'The Ashen Crescent',
    climate: 'Arid · volcanic',
    population: '~95,000 (Forgeclans)',
    threat: 4,
    ruler: 'The Anvil Lords',
    blurb: 'A scorched crescent of black ash and obsidian dunes ringing the burning Caldera. The Forgeclans hammer dawnsteel beneath the watchful eye of an ever-erupting peak. Pilgrims walk barefoot to the lava-lakes seeking visions; few return, but those who do return changed.',
    hooks: [
      'A shipment of dawnsteel was meant for the Grande Cidadela. It never left the forge.',
      'The Caldera spoke a name last night. Three pilgrims share the same dream of it.',
    ],
    polygon: '46,52 56,49 66,50 76,55 82,68 80,84 70,93 58,93 49,85 45,72 44,60',
    labelAt: { x: 63, y: 78 },
    pois: [
      { id: 'emberforge', name: 'Ember Forge',     type: 'city',    x: 67,   y: 78, note: 'The Anvil Lords\u2019 stronghold. The forge-fires have not gone out in nine centuries.' },
      { id: 'caldera',    name: 'Caldera\u2019s Eye',type: 'dungeon', x: 62.5, y: 60, note: 'The mouth of the mountain. Said to be an eye, watching back.' },
      { id: 'ashwarden',  name: 'Ashwarden Outpost', type: 'landmark', x: 73, y: 86, note: 'Last waystation before the southern obsidian dunes.' },
    ],
  },
  {
    id: 'yinxian',
    name: 'Yin Xian',
    epithet: 'The Cloud Spine',
    climate: 'Subtropical · monsoon',
    population: '~210,000',
    threat: 3,
    ruler: 'The Five Monasteries',
    blurb: 'Serpentine ridges veiled in bamboo mist. The cloud monasteries train wandering swordsages who recite poetry between their cuts. Jade dragons are said to coil the highest peaks, and the Sunken Pagoda below the southern straits is a place even the dragons will not enter.',
    hooks: [
      'A swordsage has broken her vow of wandering. She walks toward the Pagoda.',
      'The bamboo on the eastern ridge has bloomed — for the first time in eighty years.',
    ],
    polygon: '0.5,50 8,48 18,54 28,64 38,74 42,84 36,93 24,96 12,93 4,84 0.5,70',
    labelAt: { x: 17, y: 82 },
    pois: [
      { id: 'cloudmon',    name: 'Cloud Monastery', type: 'city',     x: 14, y: 66, note: 'The First Monastery. Carved into a peak that walks each century.' },
      { id: 'jadepass',    name: 'Jade Pass',       type: 'landmark', x: 30, y: 80, note: 'The only way south. A jade dragon coils above the gate.' },
      { id: 'sunkenpagoda',name: 'Sunken Pagoda',   type: 'dungeon',  x: 25, y: 91, note: 'Eleven floors below the waterline. The eleventh has never been mapped.' },
    ],
  },
  {
    id: 'lunaria',
    name: 'Lunaria',
    epithet: 'The Pale Watch',
    climate: 'Temperate · long nights',
    population: '~18,000 (Pale Order)',
    threat: 3,
    ruler: 'The Pale Order',
    blurb: 'The eastern isle, mooncradled by bone-white beaches. The Pale Order watches strange tides for omens of the second moon — the one that has not yet risen. Lunaria\u2019s nights are longer than its days, and travelers are warned: speak softly at Whisperwell.',
    hooks: [
      'A second moon was seen over Whisperwell for fourteen minutes. The Order is silent.',
      'A novice of the Pale Order has gone east. There is no east of Lunaria.',
    ],
    polygon: '76,42 82,40 89,40 95,43 99,48 99,60 98,72 95,82 88,86 81,84 77,76 75,66 75,55 75,46',
    labelAt: { x: 88, y: 67 },
    pois: [
      { id: 'palespire',  name: 'Pale Spire',     type: 'city',     x: 88, y: 65, note: 'A single white tower visible from every part of the isle.' },
      { id: 'moonshell',  name: 'Moonshell Cove', type: 'landmark', x: 84, y: 56, note: 'Tide pools that mirror constellations not yet born.' },
      { id: 'whisperwell',name: 'Whisperwell',    type: 'dungeon',  x: 93, y: 74, note: 'A well that answers in your voice. Eventually.' },
    ],
  },
];

window.MYRTAVIA_REGIONS = REGIONS;
